PA-4- Create Api service
iamdavidpetric/proker-app pull request #5
Opened 2023-02-27 10:36 UTC by iamdavidpetric

2023-02-28 06:40 UTC, iamalextodoran requested changes

2023-02-28 06:40 UTC, iamalextodoran commented on package.json
> +    "react-icons": "4.7.1",
Nono

2023-02-28 06:40 UTC, iamalextodoran commented on src/logic/api/index.js
> +  timeout: 10_000,
Set the timeout in env files (without the `_`)

2023-02-28 06:40 UTC, iamalextodoran commented on src/logic/api/index.js
> +  handleResponse: response => {
```suggestion
  handleResponse: config => {
```

2023-02-28 06:40 UTC, iamalextodoran commented on src/logic/api/index.js
> +const ownInterseptors = {
typo

2023-02-28 06:40 UTC, iamalextodoran commented on src/view/navigator/index.js
> +  <div className='min-h-screen h-screen w-screen'>
This should go into application. Revert this file.

2023-02-28 06:40 UTC, iamalextodoran commented on src/view/pages/public/Home/index.js
> +  const [error, setError] = useState([]);
Wrong defaults

2023-02-28 06:40 UTC, iamalextodoran commented on src/logic/api/index.js
> +  delete: path => {
For each crud method add a new parameter called config and initialise it with `defaultConfig`, then, where you call the method add config as the last argument.

**Notice the difference between `argument` and `parameter`** -- look it up on Google

2023-02-28 06:40 UTC, iamalextodoran commented on src/view/pages/public/Home/index.js
> +      .finally(loading.bind(null, setIsLoading));
You don't need to create a new function that uses setLoading, just bind setLoading properly

2023-02-28 13:12 UTC, iamdavidpetric commented on src/view/pages/public/Home/index.js
> +      <div className='flex flex-col justify-center items-center '>
```suggestion
      <div className='flex flex-col justify-center items-center'>
```
https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

2023-03-05 17:42 UTC, iamalextodoran commented on src/view/pages/public/Home/index.js
> +      <div className='flex flex-col justify-center items-center '>
Yes!

2023-03-05 18:36 UTC, iamalextodoran requested changes

2023-03-05 18:36 UTC, iamalextodoran commented on .env.development
> +REACT_APP_TIMEOUT=10000
What about the other envs, don't they also need a timeout?

2023-03-05 18:36 UTC, iamalextodoran commented on src/logic/api/index.js
> +  },
```suggestion
  get: (path, params = {}, config = defaultConfig) => {
    const request = api.get(path, { ...config, params });
    request.catch(Api.catchError);
    return request;
  },
```
Neat trick to have query params right into the get method

2023-03-05 18:36 UTC, iamalextodoran commented on src/view/application/index.jsx
> +  <div className='h-screen min-h-screen w-screen'>
Revert this file and apply the h-screen class directly for the body html tag into your style.css file

2023-03-05 19:03 UTC, iamalextodoran approved these changes
🌮

2023-03-05 19:04 UTC, merged